### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by RageCrezz** [CharlesStover/react-quotes-carousel#14]
There isn't an important instruction or any demo shown in the README.md.

Is there any way to insert a tutorial for this?
My IDE cannot detect which component I can import to use this extension.

Thanks in advance.

**Comment by CharlesStover** [comment]
Sorry for the delay. The default export of the package is the component.

```
import Carousel from 'react-quotes-carousel';
```

You would use it with the props in the README.
